// Generated by CoffeeScript 1.7.1
var MySound, s,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

MySound = (function() {
  MySound.prototype.songs = [];

  MySound.prototype.volume = 0.5;

  MySound.prototype.indexes = [];

  MySound.prototype.reader = new FileReader;

  MySound.prototype.audioPlayer = new Audio;

  MySound.prototype.isPlaying = false;

  function MySound() {
    this.stop = __bind(this.stop, this);
    this.play = __bind(this.play, this);
    this.fb = __bind(this.fb, this);
    this.ff = __bind(this.ff, this);
    this.handle = __bind(this.handle, this);
    this.render = __bind(this.render, this);
    this.addToList = __bind(this.addToList, this);
    this.addSong = __bind(this.addSong, this);
    $("button").on("click", this.handle);
    $("input#addSong").on("change", this.addSong);
    $(document).on("click", "li.songs", this.play);
    $("#events").on("render", this.render);
    this.reader.onload = this.addToList;
  }

  MySound.prototype.addSong = function(e) {
    var files, i, lim;
    files = e.currentTarget.files;
    i = 0;
    lim = files.length;
    $("#events").on("free", (function(_this) {
      return function() {
        if (i >= lim) {
          $("#events").trigger("render");
          return;
        }
        _this.indexes.push(files[i].name);
        _this.reader.readAsDataURL(files[i]);
        return i++;
      };
    })(this));
    return $("#events").trigger("free");
  };

  MySound.prototype.addToList = function(reader) {
    this.songs.push(this.reader.result);
    return $("#events").trigger("free");
  };

  MySound.prototype.render = function(event) {
    var song, _i, _len, _ref, _results;
    $("#songsList").html("");
    _ref = this.indexes;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      song = _ref[_i];
      _results.push($("#songsList").append("<li class='songs' id='sng-" + _i + "'>" + song + "</li>"));
    }
    return _results;
  };

  MySound.prototype.handle = function(e) {
    var id;
    id = $(e.currentTarget).attr("id");
    switch (id) {
      case "ff":
        return this.ff();
      case "fb":
        return this.fb();
      case "inputFiles":
        return $("input#addSong").trigger("click");
    }
  };

  MySound.prototype.ff = function() {
    if (this.isPlaying === !true) {
      return;
    }
    return s.audioPlayer.currentTime = s.audioPlayer.currentTime + 10;
  };

  MySound.prototype.fb = function() {
    if (this.isPlaying === !true) {
      return;
    }
    return s.audioPlayer.currentTime = s.audioPlayer.currentTime - 5;
  };

  MySound.prototype.play = function(e) {
    var id, reg;
    reg = /sng-([0-9]*)/;
    id = reg.exec(e.currentTarget.id)[1];
    this.audioPlayer.src = this.songs[id];
    this.audioPlayer.play();
    return this.isPlaying = true;
  };

  MySound.prototype.stop = function() {
    this.audioPlayer.stop();
    return this.isPlaying = false;
  };

  return MySound;

})();

s = new MySound();
